(require-extension
 syntax-case)
(require 'sound)
(import sound)
;;; Preserves high-to-low mapping
(exact->inexact (* (orbit->hertz (planet-orbit pluto)) (expt 2 35)))
(exact->inexact (* (orbit->hertz (planet-orbit neptune)) (expt 2 35)))
(exact->inexact (* (orbit->hertz (planet-orbit uranus)) (expt 2 35)))
(exact->inexact (* (orbit->hertz (planet-orbit saturn)) (expt 2 34)))
(exact->inexact (* (orbit->hertz (planet-orbit jupiter)) (expt 2 33)))
(exact->inexact (* (orbit->hertz (planet-orbit mars)) (expt 2 31)))
(exact->inexact (* (orbit->hertz (planet-orbit earth-moon-barycenter)) (expt 2 31)))
(exact->inexact (* (orbit->hertz (planet-orbit venus)) (expt 2 31)))
(exact->inexact (* (orbit->hertz (planet-orbit mercury)) (expt 2 30)))

;; (exact->inexact (* (orbit->hertz (planet-orbit pluto)) (expt 2 37)))
;; (exact->inexact (* (orbit->hertz (planet-orbit neptune)) (expt 2 36)))
;; (exact->inexact (* (orbit->hertz (planet-orbit uranus)) (expt 2 35)))
;; (exact->inexact (* (orbit->hertz (planet-orbit saturn)) (expt 2 34)))
;; (exact->inexact (* (orbit->hertz (planet-orbit jupiter)) (expt 2 33)))
;; (exact->inexact (* (orbit->hertz (planet-orbit mars)) (expt 2 31)))
;; (exact->inexact (* (orbit->hertz (planet-orbit earth-moon-barycenter)) (expt 2 30)))
;; (exact->inexact (* (orbit->hertz (planet-orbit venus)) (expt 2 29)))
;; (exact->inexact (* (orbit->hertz (planet-orbit mercury)) (expt 2 28)))
